-- category DUMMY --

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(SEQ_FM_CATEGORY_NO.NEXTVAL, '추천상품', null);

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(SEQ_FM_CATEGORY_NO.NEXTVAL, '베스트', null);

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(SEQ_FM_CATEGORY_NO.NEXTVAL, '육류', null);

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(SEQ_FM_CATEGORY_NO.NEXTVAL, '닭가슴살', 3);

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(SEQ_FM_CATEGORY_NO.NEXTVAL, '유제품', null);

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(SEQ_FM_CATEGORY_NO.NEXTVAL, '치즈', 5);

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(SEQ_FM_CATEGORY_NO.NEXTVAL, '우유', 5);

COMMIT;

SELECT *
FROM FM_CATEGORY;

-------------------------------------
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '단백질과 함께 춤을', 186, 500, 1000, 19, 3, 2, '단백질과 함께 춤을 추는 야채와 과일로 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '단백질1.jpg','단백질1.jpg');

--2
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '종합 단백질샐러드', 186, 500, 1300, 55, 3, 2, '단백질의 종합세트와 함께 어우러지는 야채의 종합 세트로 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '단백질2.jpg','단백질2.jpg');


--3
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '달걀 샐러드', 210, 500, 2200, 500, 3, 3, '단백질의 끝판왕 달걀 , 달걀의 샐러드 끝판왕으로 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '단백질3.jpg','단백질3.jpg');


--4
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '단백질 스테이크', 201, 500, 1700, 50, 3, 3, '스테이크로 만든 단백질의 끝판왕으로 맛있게 다이어트하는 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL,'단백질4.jpg','단백질4.jpg');


--5
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '연어 샐러드', 305, 500, 1999, 79, 3, 4, '새로운 단백질의 끝판왕 연어구이, 연어구이와 함께 하는 샐러드로써 헌끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '단백질5.jpg','단백질5.jpg');


--6
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '야채에 단백질 한스푼', 350, 500, 4000, 2000, 3, 4, '종합 야채의 축제에 단백질 한스푼으로 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '단백질6.jpg','단백질6.jpg');


--7
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '스테이크', 95, 500, 2500, 177, 3, 1, '단백질의 든든한 기둥 스테이크 한입으로 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '단백질7.jpg','단백질7.jpg');

INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '이재현스테이크', 95, 500, 2500, 177, 3, 1, '이재현셰프의 기막힌 스테이크');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '단백질1.jpg','단백질1.jpg');

commit; 


--1
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '닭가슴살구이볶음', 95, 500, 1000, 19, 4, 1, '닭가슴살을 미디엄으로 구워 싱싱한 야채와 함께 맛있는 한끼를 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '닭가슴살1.jpg','닭가슴살1.jpg');

--2
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '닭가슴살샐러드', 54, 500, 1300, 55, 4, 1, '국내산 닭가슴살을 얇게 썰어서 싱싱한 야채와 함께 든든한 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '닭가슴살2.jpg','닭가슴살2.jpg');


--3
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '닭가슴살샐러드2', 186, 500, 2200, 500, 4, 2, '야채의 비율을 더 높혀 더 높은 상큼함을 더해 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '닭가슴살3.jpg','닭가슴살3.jpg');


--4
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '닭가슴살샐러드3', 186, 500, 1700, 50, 4, 2, '닭가슴살과 고구마를 구워 단백함과 고소함을 함께 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL,'닭가슴살4.jpg','닭가슴살4.jpg');


--5
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '로제 닭가슴살', 205, 500, 1999, 79, 4, 3, '닭가슴살을 로제소스와 함께 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '닭가슴살5.jpg','닭가슴살5.jpg');


--6
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '레몬 닭가슴살구이', 205, 500, 4000, 2000, 4, 3, '레몬과 함께 닭가슴살 구이로써 닭가슴살의 육즙을 보다 더 부드럽게 하여 퍽퍽하지 않게 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '닭가슴살6.jpg','닭가슴살6.jpg');


--7
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '아보카도 닭가슴살 샐러드', 361, 500, 2500, 177, 4, 3, '다이어트의 신흥강자 아보카도와 함께 닭가슴살 샐러드로 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '닭가슴살7.jpg','닭가슴살7.jpg');


--8
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '닭가슴살 종합 샐러드', 370, 500, 2499, 179, 4, 3, '근육을 키우기 위한 당신을 위하여 닭가슴살과 다양한 야채와 과일로 건강과 단백질을 한번에 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '닭가슴살8.jpg','닭가슴살8.jpg');


--9
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '갈릭 닭가슴살구이', 250, 500, 1570, 9, 4, 3, '평범한 닭가슴살을 가라 갈릭 소스와 어우러진 달달한 닭가슴살로 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL,'닭가슴살9.jpg','닭가슴살9.jpg');


--10
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '야채샐러드에 닭가슴살 한스푼', 186, 500, 4000, 577, 4, 2, '야채샐러드에 닭가슴살 한스푼을 언져서 살찔 걱정 ㄴㄴ한 한끼 해결!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL,'닭가슴살10.jpg','닭가슴살10.jpg');

commit;


--1
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '과일우유', 186, 500, 1000, 19, 6, 2, '과일과 함께 우유를 먹으면 그것이 과일우유!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '우유1.jpg','우유1.jpg');

--2
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '땅콩우유', 75, 500, 1300, 55, 6, 1, '땅콩과 함께 우유를 먹으면 그것이 땅콩 우유!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '우유2.jpg','우유2.jpg');


--3
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '상큼한 우유 한잔', 205, 500, 2200, 500, 6, 3, '갓 짜낸 신선한 우유 한잔!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '우유3.jpg','우유3.jpg');


commit;


--1
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '원조치즈', 186, 500, 1000, 19, 7, 2, '치즈의 원조!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '치즈1.jpg','치즈1.jpg');

--2
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '우아한 치즈', 205, 500, 1300, 55, 7, 3, '치즈의 우아함과 함께 한잔!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '치즈2.jpg','치즈2.jpg');


--3
INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE, FM_ITEM_DETAIL)
VALUES(SEQ_FM_ITEM_NO.nextval, '종합 치즈', 86, 500, 2200, 500, 7, 1, '치즈와 함께 춤을!!');

INSERT INTO FM_ITEM_IMG
value(FM_ITEM_IMG_NO, FM_ITEM_NO, FM_ITEM_IMG_NAME, FM_ITEM_STORED_IMG_NAME)
VALUES(SEQ_FM_ITEM_IMG_NO.NEXTVAL, SEQ_FM_ITEM_NO.CURRVAL, '치즈3.jpg','치즈3.jpg');


commit;