-- FM_USER DUMMY-- 

INSERT INTO FM_USER
VALUE(FM_USER_NO, FM_USER_NICKNAME, FM_USER_EMAIL, FM_USER_PASSWORD, FM_USER_MOBILE, FM_USER_ZIP_CODE
    , FM_USER_ADDRESS, FM_USER_CRE_DATE, FM_USER_POINT)
VALUES(1, 'nkhink', 'nkhink@naver.com', '1234', '010-1234-5678', '21954', '인천광역시 연수구 청량로 222',
    SYSDATE, 50000);
    
INSERT INTO FM_USER
VALUE(FM_USER_NO, FM_USER_NICKNAME, FM_USER_EMAIL, FM_USER_PASSWORD, FM_USER_MOBILE, FM_USER_ZIP_CODE
    , FM_USER_ADDRESS, FM_USER_CRE_DATE, FM_USER_POINT)
VALUES(2, 'qudgurs', 'qudgurs@naver.com', '1234', '010-2345-6789', '21954', '인천광역시 연수구 청량로 222',
    SYSDATE, 50000);
    
INSERT INTO FM_USER
VALUE(FM_USER_NO, FM_USER_NICKNAME, FM_USER_EMAIL, FM_USER_PASSWORD, FM_USER_MOBILE, FM_USER_ZIP_CODE
    , FM_USER_ADDRESS, FM_USER_CRE_DATE, FM_USER_POINT)
VALUES(3, 'home4051', 'home4051@naver.com', '1234', '010-0123-4567', '21954', '인천광역시 연수구 청량로 222',
    SYSDATE, 50000);

INSERT INTO FM_USER
VALUE(FM_USER_NO, FM_USER_NICKNAME, FM_USER_EMAIL, FM_USER_PASSWORD, FM_USER_MOBILE, FM_USER_ZIP_CODE
    , FM_USER_ADDRESS, FM_USER_CRE_DATE, FM_USER_POINT)
VALUES(4, 'ogw12', 'ogw12@gmail.com', '1234', '010-3456-7890', '21954', '인천광역시 연수구 청량로 222',
    SYSDATE, 50000);
    
COMMIT;

SELECT *
FROM FM_USER;


-- category DUMMY --

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(1, '육류', null);

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(2, '닭가슴살', 1);

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(3, '유제품', null);

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(4, '치즈', 3);

INSERT INTO FM_CATEGORY
VALUE(FM_CATEGORY_NO, FM_CATEGORY_NAME, FM_PARENT_CATEGORY_NO)
VALUES(5, '우유', 3);

COMMIT;

SELECT *
FROM FM_CATEGORY;

-- BMI_STANDARD DUMMY -- 
-- BMI = WEIGHT / (HEIGHT * HEIGHT) * 10000

--INSERT INTO FM_BMI_STANDARD
--VALUE(FM_BMI_GRADE, FM_BMI_MIN, FM_BMI_MAX)
--VALUES(1, 0, 18.5);
--
--INSERT INTO FM_BMI_STANDARD
--VALUE(FM_BMI_GRADE, FM_BMI_MIN, FM_BMI_MAX)
--VALUES(2, 18.5, 23);
--
--INSERT INTO FM_BMI_STANDARD
--VALUE(FM_BMI_GRADE, FM_BMI_MIN, FM_BMI_MAX)
--VALUES(3, 23, 25);
--
--INSERT INTO FM_BMI_STANDARD
--VALUE(FM_BMI_GRADE, FM_BMI_MIN, FM_BMI_MAX)
--VALUES(4, 25, 99);
--
--COMMIT;
--
--SELECT *
--FROM FM_BMI_STANDARD;

-- FM_USER_BMI DUMMY -- 

INSERT INTO FM_USER_BMI
VALUE(FM_USER_BMI_NO, FM_USER_NO, FM_USER_BMI_WEIGHT, FM_USER_BMI_HEIGHT, FM_USER_BMI_GENDER
    , FM_USER_BMI_RAW, FM_USER_GOAL_BMI, FM_USER_GOAL_CALORY)
VALUES(1, 1, 85, 186, 'M', ROUND(85/(1.86*1.86),1), ROUND(85/(1.86*1.86)-1,1), 200);

INSERT INTO FM_USER_BMI
VALUE(FM_USER_BMI_NO, FM_USER_NO, FM_USER_BMI_WEIGHT, FM_USER_BMI_HEIGHT, FM_USER_BMI_GENDER
    , FM_USER_BMI_RAW, FM_USER_GOAL_BMI, FM_USER_GOAL_CALORY)
VALUES(2, 2, 85, 179, 'M', ROUND(85/(1.79*1.79),1), ROUND(85/(1.79*1.79)-1,1), 250);

INSERT INTO FM_USER_BMI
VALUE(FM_USER_BMI_NO, FM_USER_NO, FM_USER_BMI_WEIGHT, FM_USER_BMI_HEIGHT, FM_USER_BMI_GENDER
    , FM_USER_BMI_RAW, FM_USER_GOAL_BMI, FM_USER_GOAL_CALORY)
VALUES(3, 3, 67, 175, 'M', ROUND(67/(1.75*1.75),1), ROUND(67/(1.75*1.75)-1,1), 150);

INSERT INTO FM_USER_BMI
VALUE(FM_USER_BMI_NO, FM_USER_NO, FM_USER_BMI_WEIGHT, FM_USER_BMI_HEIGHT, FM_USER_BMI_GENDER
    , FM_USER_BMI_RAW, FM_USER_GOAL_BMI, FM_USER_GOAL_CALORY)
VALUES(4, 4, 90, 175, 'M', ROUND(90/(1.75*1.75),1), ROUND(90/(1.75*1.75)-1,1), 150);

COMMIT;

SELECT *
FROM FM_USER_BMI;

-- CARORY DUMMY -- 

--INSERT INTO FM_CALORY_STANDARD
--VALUE(FM_CALORY_GRADE, FM_CALORY_MIN, FM_CALORY_MAX)
--VALUES(1, 0, 100);
--
--INSERT INTO FM_CALORY_STANDARD
--VALUE(FM_CALORY_GRADE, FM_CALORY_MIN, FM_CALORY_MAX)
--VALUES(2, 100, 200);
--
--INSERT INTO FM_CALORY_STANDARD
--VALUE(FM_CALORY_GRADE, FM_CALORY_MIN, FM_CALORY_MAX)
--VALUES(3, 200, 300);
--
--INSERT INTO FM_CALORY_STANDARD
--VALUE(FM_CALORY_GRADE, FM_CALORY_MIN, FM_CALORY_MAX)
--VALUES(4, 300, 400);
--
--COMMIT;
--
--SELECT *
--FROM FM_CALORY_STANDARD;

-- ITEM DUMMY --

INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE)
VALUES(1, '신선한 닭가슴살', 186, 500, 1300, 9999, 2, 2);

INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE)
VALUES(2, '신선한 모짜렐라 치즈', 340, 800, 2000, 9999, 4, 4);

INSERT INTO FM_ITEM
VALUE(FM_ITEM_NO, FM_ITEM_NAME, FM_ITEM_CALORY, FM_ITEM_RAWPRICE, FM_ITEM_SELLPRICE, FM_ITEM_COUNT
    , FM_CATEGORY_NO, FM_CALORY_GRADE)
VALUES(3, '고지방 우유', 220, 1300, 2500, 9999, 5, 3);

SELECT *
FROM FM_ITEM;

COMMIT;


INSERT INTO fm_cart
VALUE(FM_CART_NO, FM_USER_NO, FM_ITEM_NO, FM_CART_COUNT)
VALUES(SEQ_FM_CART_NO.NEXTVAL, 1, 1, 4);

INSERT INTO fm_cart
VALUE(FM_CART_NO, FM_USER_NO, FM_ITEM_NO, FM_CART_COUNT)
VALUES(SEQ_FM_CART_NO.NEXTVAL, 1, 2, 7);

INSERT INTO fm_cart
VALUE(FM_CART_NO, FM_USER_NO, FM_ITEM_NO, FM_CART_COUNT)
VALUES(SEQ_FM_CART_NO.NEXTVAL, 1, 3, 5);

select *
from fm_cart;

commit;