
/* Drop Tables */

DROP TABLE BMI_STANDARD CASCADE CONSTRAINTS;
DROP TABLE CALORY_STANDARD CASCADE CONSTRAINTS;
DROP TABLE ORDERS_DETAIL CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE RECOMMAND CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE CATEGORYS CASCADE CONSTRAINTS;
DROP TABLE FM_USER_BMI CASCADE CONSTRAINTS;
DROP TABLE ORDERS CASCADE CONSTRAINTS;
DROP TABLE FM_USER CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_CART_CART_NO;
DROP SEQUENCE SEQ_CATEGORYS_CATEGORYS_NO;
DROP SEQUENCE SEQ_FM_USER_FM_USER_NO;
DROP SEQUENCE SEQ_ITEM_ITEM_NO;
DROP SEQUENCE SEQ_ORDERS_DETAIL_NO;
DROP SEQUENCE SEQ_ORDERS_ORDERS_NO;
DROP SEQUENCE SEQ_REPLY_REPLY_NO;
DROP SEQUENCE SEQ_REVIEW_REVIEW_NO;




/* Create Sequences */

CREATE SEQUENCE SEQ_CART_CART_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_CATEGORYS_CATEGORYS_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_FM_USER_FM_USER_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_ITEM_ITEM_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_ORDERS_DETAIL_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_ORDERS_ORDERS_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_REPLY_REPLY_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_REVIEW_REVIEW_NO INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE BMI_STANDARD
(
	BMI_GRADE number NOT NULL,
	BMI_MIN float NOT NULL,
	BMI_MAX float NOT NULL,
	PRIMARY KEY (BMI_GRADE)
);


CREATE TABLE CALORY_STANDARD
(
	CALORY_GRADE number NOT NULL,
	CARLORY_MIN float NOT NULL,
	CALORY_MAX float NOT NULL,
	PRIMARY KEY (CALORY_GRADE)
);


CREATE TABLE CART
(
	CART_NO number NOT NULL,
	CART_COUNT number NOT NULL,
	CART_ITEM varchar2(100) NOT NULL,
	CART_PRICE number NOT NULL,
	FM_USER_NO number NOT NULL,
	ITEM_NO number NOT NULL,
	CALORY_GRADE number NOT NULL,
	CONSTRAINT CART_CART_NO_PK PRIMARY KEY (CART_NO)
);


CREATE TABLE CATEGORYS
(
	CATEGORYS_NO number NOT NULL,
	CATEGORYS_NAME varchar2(30) NOT NULL,
	PARENT_CATEGORY_NO number,
	CONSTRAINT CATEGORYS_CATEGORYS_NO_PK PRIMARY KEY (CATEGORYS_NO),
	CONSTRAINT CATEGORY_CATEGORY_NAME_U UNIQUE (CATEGORYS_NAME)
);


CREATE TABLE FM_USER
(
	FM_USER_NO number NOT NULL,
	FM_USER_NICKNAME varchar2(30) NOT NULL,
	FM_USER_EMAIL varchar2(30) NOT NULL,
	FM_USER_PASSWORD varchar2(100) NOT NULL,
	FM_USER_MOBILE varchar2(13) NOT NULL,
	FM_USER_ZIP_CODE varchar2(10) NOT NULL,
	FM_USER_ADDRESS varchar2(300) NOT NULL,
	FM_USER_CRE_DATE date NOT NULL,
	FM_USER_POINT number NOT NULL,
	CONSTRAINT FM_USER_FM_USER_NO_PK PRIMARY KEY (FM_USER_NO),
	CONSTRAINT FM_USER_FM_USER_NICKNAME_U UNIQUE (FM_USER_NICKNAME),
	CONSTRAINT FM_USER_FM_USER_EMAIL_U UNIQUE (FM_USER_EMAIL),
	CONSTRAINT FM_USER_FM_USER_MOBILE_U UNIQUE (FM_USER_MOBILE)
);


CREATE TABLE FM_USER_BMI
(
	FM_USER_NO number NOT NULL,
	FM_USER_WEIGHT float NOT NULL,
	FM_USER_HEIGHT float NOT NULL,
	-- M / F
	FM_USER_GENDER varchar2(2) NOT NULL,
	FM_USER_BMI float NOT NULL,
	BMI_GRADE number NOT NULL,
	CONSTRAINT BMI_STANDARD_BMI_GRADE_PK PRIMARY KEY (FM_USER_NO, BMI_GRADE)
);


CREATE TABLE ITEM
(
	ITEM_NO number NOT NULL,
	ITEM_NAME varchar2(100) NOT NULL,
	ITEM_CALORY varchar2(300) NOT NULL,
	ITEM_RAWPRICE number NOT NULL,
	ITEM_SELLPRICE number NOT NULL,
	ITEM_COUNT number NOT NULL,
	ITEM_THUMBNAIL varchar2(4000) NOT NULL,
	ITEM_PICTURE varchar2(4000) NOT NULL,
	CATEGORYS_NO number NOT NULL,
	CALORY_GRADE number NOT NULL,
	CONSTRAINT ITEM__ITEM_NO_PK PRIMARY KEY (ITEM_NO, CALORY_GRADE)
);


CREATE TABLE ORDERS
(
	ORDERS_NO number NOT NULL,
	ORDERS_PRICE number NOT NULL,
	ORDERS_NAME varchar2(150) NOT NULL,
	ORDERS_TOTALPRICE number,
	FM_USER_NO number NOT NULL,
	CONSTRAINT ORDER_ORDER_NO_PK PRIMARY KEY (ORDERS_NO)
);


CREATE TABLE ORDERS_DETAIL
(
	ORDERS_DETAIL_NO number NOT NULL,
	ORDERS_NO number NOT NULL,
	ITEM_NO number NOT NULL,
	CART_NO number,
	CALORY_GRADE number NOT NULL,
	CONSTRAINT ORDERS_DETAIL_NO_PK PRIMARY KEY (ORDERS_DETAIL_NO)
);


CREATE TABLE RECOMMAND
(
	FM_USER_NO number NOT NULL,
	ITEM_NO number NOT NULL,
	BMI_GRADE number NOT NULL,
	CALORY_GRADE number NOT NULL
);


CREATE TABLE REPLY
(
	REPLY_NO number NOT NULL,
	REPLY_TITLE varchar2(100) NOT NULL,
	FM_USER_NO number NOT NULL,
	REPLY_CONTENT varchar2(300) NOT NULL,
	REPLY_CRE_DATE date NOT NULL,
	PARENT_REPLY_NO number,
	REVIEW_NO number NOT NULL,
	CONSTRAINT REPLY_REPLY_NO_PK PRIMARY KEY (REPLY_NO)
);


CREATE TABLE REVIEW
(
	REVIEW_NO number NOT NULL,
	REVIEW_TITLE varchar2(100) NOT NULL,
	FM_USER_NO number NOT NULL,
	REVIEW_CONTENT varchar2(300) NOT NULL,
	REVIEW_IMAGE varchar2(4000) NOT NULL,
	REVIEW_CRE_DATE date NOT NULL,
	REVIEW_MOD_DATE date NOT NULL,
	ITEM_NO number NOT NULL,
	BMI_GRADE number NOT NULL,
	CALORY_GRADE number NOT NULL,
	CONSTRAINT REVIEW_REVIEW_NO_PK PRIMARY KEY (REVIEW_NO)
);



/* Create Foreign Keys */

ALTER TABLE ORDERS_DETAIL
	ADD FOREIGN KEY (CART_NO)
	REFERENCES CART (CART_NO)
;


ALTER TABLE ITEM
	ADD FOREIGN KEY (CATEGORYS_NO)
	REFERENCES CATEGORYS (CATEGORYS_NO)
;


ALTER TABLE CART
	ADD FOREIGN KEY (FM_USER_NO)
	REFERENCES FM_USER (FM_USER_NO)
;


ALTER TABLE FM_USER_BMI
	ADD FOREIGN KEY (FM_USER_NO)
	REFERENCES FM_USER (FM_USER_NO)
;


ALTER TABLE ORDERS
	ADD FOREIGN KEY (FM_USER_NO)
	REFERENCES FM_USER (FM_USER_NO)
;


ALTER TABLE REPLY
	ADD FOREIGN KEY (FM_USER_NO)
	REFERENCES FM_USER (FM_USER_NO)
;


ALTER TABLE REVIEW
	ADD FOREIGN KEY (FM_USER_NO)
	REFERENCES FM_USER (FM_USER_NO)
;


ALTER TABLE RECOMMAND
	ADD FOREIGN KEY (FM_USER_NO, BMI_GRADE)
	REFERENCES FM_USER_BMI (FM_USER_NO, BMI_GRADE)
;


ALTER TABLE REVIEW
	ADD FOREIGN KEY (FM_USER_NO, BMI_GRADE)
	REFERENCES FM_USER_BMI (FM_USER_NO, BMI_GRADE)
;


ALTER TABLE CART
	ADD FOREIGN KEY (ITEM_NO, CALORY_GRADE)
	REFERENCES ITEM (ITEM_NO, CALORY_GRADE)
;


ALTER TABLE ORDERS_DETAIL
	ADD FOREIGN KEY (ITEM_NO, CALORY_GRADE)
	REFERENCES ITEM (ITEM_NO, CALORY_GRADE)
;


ALTER TABLE RECOMMAND
	ADD FOREIGN KEY (ITEM_NO, CALORY_GRADE)
	REFERENCES ITEM (ITEM_NO, CALORY_GRADE)
;


ALTER TABLE REVIEW
	ADD FOREIGN KEY (ITEM_NO, CALORY_GRADE)
	REFERENCES ITEM (ITEM_NO, CALORY_GRADE)
;


ALTER TABLE ORDERS_DETAIL
	ADD FOREIGN KEY (ORDERS_NO)
	REFERENCES ORDERS (ORDERS_NO)
;


ALTER TABLE REPLY
	ADD FOREIGN KEY (REVIEW_NO)
	REFERENCES REVIEW (REVIEW_NO)
;

COMMIT;